name: GitHubActions-demo
env:
  APPLICATION_NAME   : "MyFlask"
  DRPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Helo World 1
      run: echo "Helo World 1"

  my_deploy: 
    runs-on: ubuntu-latest
    needs: [my_testing]

    steps:
    - name: Print Hello World 2
      run: echo "Hello World 2" 
    
